AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  ForceEventBridge:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
      - auto
  VpcId:
    Type: String
    Default: ''
  Subnet:
    Type: List<String>
    Default: ''
  S3Bucket:
    Type: String
    Default: ''
  S3Prefix:
    Type: String
    Default: ''
  

Resources:
  ProcessUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: process_url
      CodeUri: functions/process_url/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 1600

  RetrieveSecretsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: retrieve_secrets
      CodeUri: functions/retrieve_secrets/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          Region: !Ref AWS::Region
          SecretName: !Sub "pxl-intern-disneyscrap-${Environment}"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${S3Bucket}/${S3Prefix}/*"
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:pxl-intern-disneyscrap-${Environment}-*"

  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/scrap.asl.json
      DefinitionSubstitutions:
        ProcessUrlFunctionArn: !GetAtt ProcessUrlFunction.Arn
        RetrieveSecretsFunctionArn: !GetAtt RetrieveSecretsFunction.Arn
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt ProcessUrlFunction.Arn
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt RetrieveSecretsFunction.Arn